title: Walmart Sales Analysis
logo: assets/images/Findings Q1.png
show_downloads: True
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
